name: Publish package

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    name: Publish kataloger to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*

  create-release:
    name: Create GitHub release
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Read package version
      id: read_version
      run: |
        version=$(grep "^__version__" src/kataloger/__init__.py | sed -E 's/^.*"([0-9A-Za-z\-_+.]+)".*$/\1/')
        if [ -z "$version" ]; then
          echo "ERROR: Can't find package version!"
          exit 1
        fi
        echo "::set-output name=package_version::$version"

    - uses: softprops/action-gh-release@v1
      name: Create release
      with:
        body_path: ${{ github.workspace }}/changelog.md
        name: v${{ steps.read_version.outputs.package_version }}
        tag_name: v${{ steps.read_version.outputs.package_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
