name: Publish package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    name: Publish kataloger to PyPI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run:
        twine upload dist/*

  create-release:
    name: Create GitHub release
    needs: publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: SebRollen/toml-action@v1.0.2
      id: read_version
      with:
        file: pyproject.toml
        field: project.version

    - uses: softprops/action-gh-release@v1
      name: Create release
      with:
        body_path: ${{ github.workspace }}/changelog.md
        name: v${{ steps.read_version.outputs.value }}
        tag_name: v${{ steps.read_version.outputs.value }}
        token: ${{ secrets.GITHUB_TOKEN }}
