name: Run tests

on: [ push, pull_request ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff==0.5.5

    - name: Run ruff check
      run: ruff check --output-format=github

  run-tests:
    needs: [ruff]
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python_version: [ 3.8, 3.9, 3.10, 3.11, 3.12 ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python_version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: |
        pytest
